update cashier

diff --git a/bin/cashier b/bin/cashier
--- a/bin/cashier
+++ b/bin/cashier
@@ -38,14 +38,26 @@ run_script() {
 }
 
 sub_build(){
-  basePath="${1:-$PWD}"
   modified=false
   isCDN=false
   isParent=false
   isDesign=false
 
+  checkSubdesigns=false
+  while getopts 'ts' flag; do
+    case "${flag}" in
+      s) checkSubdesigns=true ;;
+      t) TYPE="${OPTARG}" ;;
+      *) echo "flag not found"
+        exit 1 ;;
+    esac
+    shift $((OPTIND - 1))
+  done
+
+  basePath="${1:-$PWD}"
+
   elapsedTime=$(( $(date +%s) - $startTime ))
-  echo -e "$unchecked basePath: $basePath"
+  echo -e "$unchecked root: $basePath"
 
   if [[ "${basePath##*/}" == "cdn" ]]; then
     isCDN=true
@@ -81,28 +93,42 @@ sub_build(){
     done
   fi
 
+  if [ "$checkSubdesigns" == true ]; then
+    for d in "$basePath"/subdesigns/*/; do
+      (
+      sub_build "$d"
+      )
+    done
+  fi
+
+
   # skip if no package.json
   if [ ! -f "$basePath"/package.json ]; then
     echo -ne "\033[1A\r\033[K"
-    echo -e "$skipped basePath: $basePath"
+    echo -e "$skipped root: $basePath"
     return
   fi
 
   # check if cache file exists
   if [ ! -f "$basePath"/"$cacheFile" ]; then
     echo -ne "\033[1A\r\033[K"
-    echo -e "$create basePath: $basePath"
+    echo -e "$create root: $basePath"
     run_script "$basePath"
     exit
   fi
 
   cacheTime=$(cat "$basePath"/"$cacheFile")
-  allFiles=$(find "$basePath" -type f -name "*" -not -name "*.log" -not -name "*.lock" -not -path "**/subdesigns/*" -not -path "**/.*/*")
+  ignoredPaths=("**/subdesigns/*" "**/node_modules/*")
+  allFiles=$(find "$basePath" -type f -name "*" -not -name "*.log" -not -name "*.lock" -not -path "$ignoredPaths" -not -path "**/.*/*")
 
   echo ""
   for f in $allFiles; do
     echo -ne "\033[1A\r\033[K"
+    # disable line wrap
+    tput rmam
     echo -e "$f"
+    # enable line wrap
+    tput smam
     fileTime=$(date -r "$f" +%s)
 
     # compare last modified time to time in cache
@@ -116,11 +142,11 @@ sub_build(){
 
   if [ "$modified" = true ]; then
     echo -ne "\033[1A\r\033[K"
-    echo -e "$changed basePath: $basePath"
+    echo -e "$changed root: $basePath"
     run_script "$basePath"
   else
     echo -ne "\033[1A\r\033[K"
-    echo -e "$passed basePath: $basePath"
+    echo -e "$passed root: $basePath"
   fi
 
 }
@@ -129,6 +155,7 @@ sub_build(){
 
 
 # boilerplate below
+#########################################################################################
 
 # print the name & version
 sub_version(){
